export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SINGLE_PRODUCTS = "GET_SINGLE_PRODUCTS";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_RPDUCT = "DELETE_RPDUCT";